language: android
jdk:
  - oraclejdk8
  - oraclejdk7

android:
  components:
    - platform-tools
    - tools
    - android-23
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-google_play_services

  licenses:
    - '.+'

script: ./gradlew build

cache:
  directories:
    - $HOME/.gradle
  timeout: 86400