language: android
jdk:
  - oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - android-24
    - build-tools-25.0.0
    - extra-android-m2repository
    - extra-google-google_play_services

  licenses:
    - '.+'

script: ./gradlew build

cache:
  directories:
    - $HOME/.gradle
  timeout: 86400